# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngo', '0002_auto_20180317_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='to',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
