# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngo', '0003_auto_20180317_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fro',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='to',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
